[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -DCORE_DEBUG_LEVEL=0
; Optional quality-of-life
; upload_speed = 921600
; monitor_filters = time, colorize

lib_deps =
  adafruit/Adafruit SSD1306@^2.5.10
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit BusIO@^1.16.2
  Chris--A/Keypad@^3.1.1

