[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
  -D OLED_RESET=-1
  -D LORA_BAND=433E6
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0
  adafruit/Adafruit SSD1306 @ ^2.5.10
  adafruit/Adafruit GFX Library @ ^1.11.10
  mikalhart/TinyGPSPlus @ ^1.0.3
  Chris--A/Keypad @ ^3.1.1

